### ISSUE TITLE
【报错】ERROR：JellyfinUtil:更新对象API,服务器错误: 400

### ISSUE THREAD

**Issue by shanshilaoseng** [Wizzercn/jellyfin_pinyin#10]
环境：
jellyfin：10.8.13
wizzer/jellyfin_pinyin:latest（v2.1）

结果：
ERROR：JellyfinUtil:更新对象API,服务器错误: 400

**Comment by Wizzercn** [comment]
虚拟机网络类型是host么？IP和端口是否能正常访问？
