### ISSUE TITLE
【报错】ERROR：JellyfinUtil:更新对象API,服务器错误: 400

### ISSUE THREAD

**Issue by Huzhixin00** [Wizzercn/jellyfin_pinyin#11]
上面那个老哥的JellyfinUtil 400报错我也遇到了，查了下JellyFin API 文档发现问题出在这一行
https://github.com/Wizzercn/jellyfin_pinyin/blob/main/src/JellyfinHandler.py#L101

Jellyfin 的 UpdateItem API 的 LockedFields 字段是 Enum，只支持 [ "Cast" "Genres" "ProductionLocations" "Studios" "Tags" "Name" "Overview" "Runtime" "OfficialRating" ] 这些字段，如果直接插入 SortName 就会报错：
https://api.jellyfin.org/#tag/ItemUpdate/operation/UpdateItem

目前我的解决方案是直接注释掉这一行就可以用了。

**Comment by Wizzercn** [comment]
```
                    if "emby" in self.domain:
                        item_detail["LockedFields"] = ["SortName"]
```

加了个判断
