### ISSUE TITLE
请问剧集拼音该如何操作

### ISSUE THREAD

**Issue by CleverMod** [Wizzercn/jellyfin_pinyin#4]
剧集自动转换的拼音是转换了每集的title   剧集的title没有进行转化拼音

**Comment by Wizzercn** [comment]
怎么复现呢？我这里看是正常的

**Comment by Wizzercn** [comment]
新增版本：[v1.6_arm](https://hub.docker.com/layers/wizzer/jellyfin_pinyin/v1.6_arm/images/sha256-aa5a2dd1b652c0b3364f188350efb9a0f56288ef1149a7a98bc789aea5e710bb?context=repo)

新增参数：SKIP   （是否跳过已处理的标题），请把 SKIP 设置为 false，重新生成下看看？

**Comment by Wizzercn** [comment]
另外 jellyfin 版本号多少？

**Comment by CleverMod** [comment]
jellyfin版本号10.8.7     处理剧情的日志截图    可以看到处理的都是每一集的title  没有处理该剧的名称
![1](https://user-images.githubusercontent.com/24726890/231341593-edff75a6-72c3-432e-a294-e56ee4fc507a.png)

**Comment by Wizzercn** [comment]
v1.7_arm 已修复

**Comment by Wizzercn** [comment]
v1.8_arm 把 SKIP 默认值设为 true

**Comment by CleverMod** [comment]
@Wizzercn 大佬威武 十分感谢
