### ISSUE TITLE
最新版本在剧集拼音上仍存在问题

### ISSUE THREAD

**Issue by daixuan201** [Wizzercn/jellyfin_pinyin#5]
有部分剧集排序失效。docker强行回退到1.0版本后有效，但dockerhub上似乎只留下了1.5版本，之前的版本下架了？有点担心会不会失灵

**Comment by Wizzercn** [comment]
版本功能变化不大，所以把老的给删了，，最近就更新了 PinyinUtil 类，
剧集名称是什么？方便用docker下的  wizzer/myfiles  生成目录结构贴一下？

**Comment by Wizzercn** [comment]
v1.7 已修复
