### ISSUE TITLE
关于“跳过”的逻辑

### ISSUE THREAD

**Issue by zhui22222** [Wizzercn/jellyfin_pinyin#6]
看了下源码，现在的逻辑是判断短标题是否为空，这样的话如果短标题已有内容就算不对也会自动跳过，是不是可以改为判断已有内容和需填入内容是否一致，一致的跳过，不一致的填入？

**Comment by Wizzercn** [comment]
docker 环境变量 ：SKIP = false

可以设置为false，全部重新生成，可以直接覆盖。

**Comment by zhui22222** [comment]
设为false就没法跳过已经处理过的文件了，是否太过简单粗暴了

**Comment by Wizzercn** [comment]
@zhui22222 设为false 运行一次后，改回true，需要再改为false（相信后面都不需要改了）

**Comment by zhui22222** [comment]
> @zhui22222 设为false 运行一次后，改回true，需要再改为false（相信后面都不需要改了）
我用了nastool，削刮完短标题会默认填入中文的标题，如果用true的话，等于没有任何作用，所以才提出这个问题，希望能完美解决这个问题啊，或者能否再增加一个选项，默认可以不打开，需要的打开就能用，万分感谢！

**Comment by Wizzercn** [comment]
@zhui22222 [v1.9](https://hub.docker.com/layers/wizzer/jellyfin_pinyin/v1.9/images/sha256-93a1044ff6ca0c2f15dde3e602ee7291f6ba0185b872c1cc4cfefbf2244a6209?context=repo)
