### ISSUE TITLE
不能单独给emby使用

### ISSUE THREAD

**Issue by daixuan201** [Wizzercn/jellyfin_pinyin#7]
最近从jellyfin转到了emby来做媒体库，发现了一个有意思的地方。这个docker给jellyfin使用是没问题的，但是给emby排序就不起作用；如果同时开着emby和jellyfin（媒体库文件夹是同一个），给jellyfin排序之后，emby的排序也就弄好了。不知道作者与没有意向适配一下emby

**Comment by Wizzercn** [comment]
@daixuan201 我抽空跑一下emby，看看能不能做兼容

**Comment by daixuan201** [comment]
> @daixuan201 可能是emby的bug，我试了各种API参数都不行，包括LockedFields、SortName、ForcedSortName，但通过它的管理后台修改是OK的，建议你更换版本。

是更换emby版本吗？还是变更jellyfin_pinyin的版本？

**Comment by Wizzercn** [comment]
已支持 emby 4.8.8.0，主要问题是 LockedFields = [ "SortName" ]，只能设置这个字段，其他会造成 locked不生效。

**Comment by flamesky80** [comment]
> 已支持 emby 4.8.8.0，主要问题是 LockedFields = [ "SortName" ]，只能设置这个字段，其他会造成 locked不生效。

请问这个 LockedFields = [ "SortName" ] 是一个环境变量，需要创建docker的时候配置吗？

**Comment by Wizzercn** [comment]
@flamesky80 不需要，那只是对问题的描述。
