### ISSUE TITLE
未获取到管理员用户

### ISSUE THREAD

**Issue by yanyuandaxia** [Wizzercn/jellyfin_pinyin#9]
版本：10.8.10

操作系统：Linux

架构：X64

`[INFO ] 23:13:16.592 [main] org.nutz.ioc.impl.NutIoc - ... NutIoc init complete
[INFO ] 23:13:16.614 [main] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 扫描媒体库: 
[INFO ] 23:13:16.614 [main] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 服务器地址 http://127.0.0.1:8096
[INFO ] 23:13:16.616 [main] org.nutz.boot.NbApp - NB started : 93ms
[ERROR] 23:13:26.631 [pool-2-thread-1] cn.wizzer.jellyfin.pinyin.utils.JellyfinUtil - 请检查服务是否启动 http://127.0.0.1:8096
[ERROR] 23:13:26.631 [pool-2-thread-1] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 未获取到管理员用户
`

已经设置了api key，jellyfin 可以在http://localhost:8096正常使用，但是报如上错误。

命令行中的完整记录是

`23:13:16,444 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
23:13:16,445 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
23:13:16,445 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/jellyfin_pinyin.jar!/logback.xml]
23:13:16,451 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3701eaf6 - URL [jar:file:/app/jellyfin_pinyin.jar!/logback.xml] is not of type file
23:13:16,493 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:13:16,493 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
23:13:16,494 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
23:13:16,520 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
23:13:16,520 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
23:13:16,520 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
23:13:16,521 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [java] to false
23:13:16,521 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
23:13:16,521 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
23:13:16,521 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
23:13:16,521 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@627551fb - Registering current configuration as safe fallback point

[INFO ] 23:13:16.541 [main] org.nutz.boot.banner.SimpleBannerPrinter - 
 _   _ ______                                      ___   
| \ | || ___ \  ______ ______ ______ ______ ______| \ \  
|  \| || |_/ / |______|______|______|______|______| |\ \ 
| . ` || ___ \  ______ ______ ______ ______ ______| | > >
| |\  || |_/ / |______|______|______|______|______| |/ / 
\_| \_/\____/                                     |_/_/  
  
:: Nutz Boot ::   (2.4.2.v20201205)
[INFO ] 23:13:16.554 [main] org.nutz.boot.config.impl.PropertiesConfigureLoader - Properties NotFound - application.properties
[INFO ] 23:13:16.581 [main] org.nutz.ioc.loader.annotation.AnnotationIocLoader -  > scan 'cn.wizzer'
[INFO ] 23:13:16.583 [main] org.nutz.ioc.loader.annotation.AnnotationIocLoader -    > add 'mainLauncher                            ' - cn.wizzer.jellyfin.pinyin.MainLauncher
[INFO ] 23:13:16.586 [main] org.nutz.ioc.loader.annotation.AnnotationIocLoader -    > add 'jellyfinHandler                         ' - cn.wizzer.jellyfin.pinyin.JellyfinHandler
[INFO ] 23:13:16.587 [main] org.nutz.ioc.loader.annotation.AnnotationIocLoader -  > scan 'org.nutz.boot.starter'
[WARN ] 23:13:16.589 [main] org.nutz.ioc.loader.annotation.AnnotationIocLoader - NONE @IocBean found!! Check your ioc configure!! packages=[org.nutz.boot.starter]
[INFO ] 23:13:16.590 [main] org.nutz.boot.NbApp - Configure Manual:
|id  |key                                     |required  |Possible Values     |Default   |Description         |                                starters|
|----|----------------------------------------|----------|--------------------|----------|--------------------|----------------------------------------|
[INFO ] 23:13:16.592 [main] org.nutz.ioc.impl.NutIoc - ... NutIoc init complete
[INFO ] 23:13:16.614 [main] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 扫描媒体库: 
[INFO ] 23:13:16.614 [main] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 服务器地址 http://127.0.0.1:8096
[INFO ] 23:13:16.616 [main] org.nutz.boot.NbApp - NB started : 93ms
[ERROR] 23:13:26.631 [pool-2-thread-1] cn.wizzer.jellyfin.pinyin.utils.JellyfinUtil - 请检查服务是否启动 http://127.0.0.1:8096
[ERROR] 23:13:26.631 [pool-2-thread-1] cn.wizzer.jellyfin.pinyin.JellyfinHandler - 未获取到管理员用户
`

**Comment by nosiop** [comment]
因为在docker内部，使用http://127.0.0.1:8096 访问不到docker外的服务，所以需要使用http://宿主机IP:8096才可以进行方文

**Comment by yanyuandaxia** [comment]
谢谢您，我周末的时候试一下，忘记了这点，非常感谢！

**Comment by yanyuandaxia** [comment]
> 因为在docker内部，使用http://127.0.0.1:8096 访问不到docker外的服务，所以需要使用[http://宿主机IP:8096才可以进行方文](http://%E5%AE%BF%E4%B8%BB%E6%9C%BAIP:8096%E6%89%8D%E5%8F%AF%E4%BB%A5%E8%BF%9B%E8%A1%8C%E6%96%B9%E6%96%87)

谢谢您，我周末的时候试一下，忘记了这点，非常感谢！

**Comment by Wizzercn** [comment]
网络设置为 host，要不访问不了 127.0.0.1

**Comment by yanyuandaxia** [comment]
非常感谢！已经可以正常使用了，忘记把这个标记为完成了。
